# Generated by Django 4.2.3 on 2023-07-21 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmortizationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amortization_system', models.CharField(help_text='Sistema de amortização', max_length=300, verbose_name='Sistema de amortização')),
                ('amortization_system_description', models.CharField(help_text='Descrição do sistema de amortização', max_length=50, verbose_name='Descrição do sistema de amortização')),
            ],
            options={
                'verbose_name': 'Sistema de amortização',
                'verbose_name_plural': 'Sistemas de amortização',
            },
        ),
        migrations.CreateModel(
            name='AmotizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amortization_type', models.CharField(help_text='Tipo de amortização', max_length=300, verbose_name='Tipo de amortização')),
                ('amortization_type_description', models.CharField(help_text='Descrição do tipo de amortização', max_length=50, verbose_name='Descrição do tipo de amortização')),
            ],
            options={
                'verbose_name': 'Tipo de amortização',
                'verbose_name_plural': 'Tipos de amortização',
            },
        ),
        migrations.CreateModel(
            name='ContractTermUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_term_unit', models.CharField(help_text='Unidade de prazo do contrato', max_length=1, verbose_name='Unidade de prazo do contrato')),
                ('contract_term_unit_description', models.CharField(help_text='Descrição da unidade de prazo do contrato', max_length=50, verbose_name='Descrição da unidade de prazo do contrato')),
            ],
            options={
                'verbose_name': 'Unidade de prazo do contrato',
                'verbose_name_plural': 'Unidades de prazo do contrato',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(error_messages={'unique': 'Ja existe um contrato com este número'}, help_text='Número de contrato', max_length=300, unique=True, verbose_name='Número de contrato')),
                ('contract_name', models.CharField(help_text='Nome do contrato', max_length=300, verbose_name='Nome do contrato')),
                ('contract_description', models.TextField(blank=True, help_text='Descrição do contrato', max_length=300, verbose_name='Descrição do contrato')),
                ('contract_start_date', models.DateField(help_text='Data de início do contrato', verbose_name='Data de início do contrato')),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Taxa de juros', max_digits=5, verbose_name='Taxa de juros')),
                ('contract_value', models.DecimalField(decimal_places=2, help_text='Valor do contrato', max_digits=20, verbose_name='Valor do contrato')),
                ('contract_file', models.FileField(blank=True, help_text='Arquivo do contrato', null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Arquivo do contrato')),
                ('contract_term', models.IntegerField(help_text='Prazo do contrato', verbose_name='Prazo do contrato')),
                ('contract_end_date', models.DateField(blank=True, help_text='Data de término do contrato', null=True, verbose_name='Data de término do contrato')),
                ('contract_status', models.BooleanField(default=True, help_text='Status do contrato', verbose_name='Status do contrato')),
                ('contract_created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do contrato', verbose_name='Data de criação do contrato')),
                ('contract_updated_at', models.DateTimeField(auto_now=True, help_text='Data de atualização do contrato', verbose_name='Data de atualização do contrato')),
                ('contract_installment_value', models.DecimalField(decimal_places=2, help_text='Valor da parcela', max_digits=20, verbose_name='Valor da parcela')),
                ('contract_installment_number', models.IntegerField(help_text='Número de parcelas', verbose_name='Número de parcelas')),
                ('contract_installment_start_date', models.DateField(help_text='Data de início das parcelas', verbose_name='Data de início das parcelas')),
                ('contract_installment_end_date', models.DateField(help_text='Data de término das parcelas', verbose_name='Data de término das parcelas')),
                ('amortization_type', models.ForeignKey(blank=True, help_text='Tipo de amortização', null=True, on_delete=django.db.models.deletion.SET_NULL, to='revcontract.amotizationtype', verbose_name='Tipo de amortização')),
                ('contract_created_by', models.ForeignKey(blank=True, help_text='Criado por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('contract_customer', models.ForeignKey(blank=True, help_text='Cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer', verbose_name='Cliente')),
                ('contract_owner', models.ForeignKey(blank=True, help_text='Dono do contrato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_owner', to=settings.AUTH_USER_MODEL, verbose_name='Dono do contrato')),
                ('contract_term_unit', models.ForeignKey(blank=True, help_text='Unidade de prazo do contrato', null=True, on_delete=django.db.models.deletion.SET_NULL, to='revcontract.contracttermunit', verbose_name='Unidade de prazo do contrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
