# Generated by Django 4.2.3 on 2023-07-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revcontract', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmotizationType',
            new_name='AmortizationType',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_bcb_sgs_code',
            field=models.IntegerField(blank=True, help_text='Código BCB SGS', null=True, verbose_name='Código BCB SGS'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(help_text='Número de contrato', max_length=300, verbose_name='Número de contrato'),
        ),
    ]
