# Generated by Django 4.2.3 on 2023-07-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revcontract', '0002_rename_amotizationtype_amortizationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortizationtype',
            name='amortization_type',
            field=models.CharField(help_text='Tipo de amortização', max_length=50, verbose_name='Tipo de amortização'),
        ),
        migrations.AlterField(
            model_name='amortizationtype',
            name='amortization_type_description',
            field=models.CharField(help_text='Descrição do tipo de amortização', max_length=500, verbose_name='Descrição do tipo de amortização'),
        ),
    ]
