# Generated by Django 4.2.3 on 2023-07-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revcontract', '0003_alter_amortizationtype_amortization_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_amortization_system',
            field=models.ForeignKey(blank=True, help_text='Sistema de amortização', null=True, on_delete=django.db.models.deletion.SET_NULL, to='revcontract.amortizationsystem', verbose_name='Sistema de amortização'),
        ),
    ]
