# Generated by Django 4.2.3 on 2023-07-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revcontract', '0004_contract_contract_amortization_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCBSGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(help_text='Código BCB SGS', verbose_name='Código BCB SGS')),
                ('name', models.CharField(help_text='Nome do indicador', max_length=300, verbose_name='Nome do indicador')),
                ('unit', models.CharField(help_text='Unidade do indicador', max_length=300, verbose_name='Unidade do indicador')),
                ('frequency', models.CharField(help_text='Frequência do indicador', max_length=300, verbose_name='Frequência do indicador')),
                ('start_date', models.DateField(help_text='Data de início do indicador', verbose_name='Data de início do indicador')),
                ('end_date', models.DateField(help_text='Data de término do indicador', verbose_name='Data de término do indicador')),
                ('source', models.CharField(help_text='Fonte do indicador', max_length=300, verbose_name='Fonte do indicador')),
            ],
        ),
        migrations.CreateModel(
            name='ContractAlternatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(blank=True, help_text='Contrato', null=True, on_delete=django.db.models.deletion.SET_NULL, to='revcontract.contract', verbose_name='Contrato')),
                ('contract_amortization_system', models.ForeignKey(blank=True, help_text='Sistema de amortização', null=True, on_delete=django.db.models.deletion.SET_NULL, to='revcontract.amortizationsystem', verbose_name='Sistema de amortização')),
            ],
            options={
                'verbose_name': 'Alternativa de contrato',
                'verbose_name_plural': 'Alternativas de contrato',
            },
        ),
    ]
