# Generated by Django 4.2.3 on 2023-07-27 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revcontract', '0005_bcbsgs_contractalternatives'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bcbsgs',
            options={'verbose_name': 'Indicador BCB SGS', 'verbose_name_plural': 'Indicadores BCB SGS'},
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='amortization_type',
            new_name='contract_amortization_type',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='interest_rate',
            new_name='contract_interest_rate',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_abusive',
            field=models.BooleanField(default=False, help_text='Contrato abusivo', verbose_name='Contrato abusivo'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_super_abusive',
            field=models.BooleanField(default=False, help_text='Contrato super abusivo', verbose_name='Contrato super abusivo'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_bcb_sgs_code',
            field=models.ForeignKey(blank=True, help_text='Código BCB SGS', null=True, on_delete=django.db.models.deletion.SET_NULL, to='revcontract.bcbsgs', verbose_name='Código BCB SGS'),
        ),
    ]
