# Generated by Django 4.2.3 on 2023-07-27 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revcontract', '0006_alter_bcbsgs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcbsgs',
            name='code',
            field=models.IntegerField(help_text='Código BCB SGS', unique=True, verbose_name='Código BCB SGS'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_bcb_sgs_code',
            field=models.ForeignKey(blank=True, help_text='Código BCB SGS', null=True, on_delete=django.db.models.deletion.SET_NULL, to='revcontract.bcbsgs', to_field='code', verbose_name='Código BCB SGS'),
        ),
    ]
