# Generated by Django 4.2.3 on 2023-07-27 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revcontract', '0007_alter_bcbsgs_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bcbsgs',
            name='id',
        ),
        migrations.AlterField(
            model_name='bcbsgs',
            name='code',
            field=models.IntegerField(help_text='Código BCB SGS', primary_key=True, serialize=False, unique=True, verbose_name='Código BCB SGS'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_bcb_sgs_code',
            field=models.ForeignKey(blank=True, help_text='Código BCB SGS', null=True, on_delete=django.db.models.deletion.SET_NULL, to='revcontract.bcbsgs', verbose_name='Código BCB SGS'),
        ),
    ]
