# Generated by Django 4.2.3 on 2023-07-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revcontract', '0008_remove_bcbsgs_id_alter_bcbsgs_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_bcb_sgs_code',
            field=models.ForeignKey(blank=True, help_text='Código BCB SGS', null=True, on_delete=django.db.models.deletion.SET_NULL, to='revcontract.bcbsgs', unique=True, verbose_name='Código BCB SGS'),
        ),
    ]
