# Generated by Django 4.2.3 on 2023-07-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revcontract', '0009_alter_contract_contract_bcb_sgs_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_bcb_sgs_code',
            field=models.IntegerField(help_text='Código BCB SGS', verbose_name='Código BCB SGS'),
        ),
    ]
