# Generated by Django 4.2.3 on 2023-07-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revcontract', '0011_alter_contract_contract_bcb_sgs_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_interest_rate',
            field=models.FloatField(help_text='Taxa de juros do contrato', verbose_name='Taxa de juros do contrato'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, help_text='Número de contrato', max_length=300, null=True, verbose_name='Número de contrato'),
        ),
        migrations.DeleteModel(
            name='ContractAlternatives',
        ),
    ]
